$axure.loadCurrentPage({
  "url":"student.html",
  "generationDate":new Date(1528444894216.04),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9fcc1975e2ee4476a2ef6c4b10a6d271",
    "type":"Axure:Page",
    "name":"student",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"23ffbefc7ab64a2e9fa4445a49579f02",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCFF},
            "location":{
              "x":140,
              "y":10},
            "size":{
              "width":578,
              "height":580}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"162ea1746bd44a86b83ca09f3abb360f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCFF},
                "location":{
                  "x":140,
                  "y":10},
                "size":{
                  "width":578,
                  "height":580}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/student/u0.png"}},
{
          "id":"cf9ce46af26241c69effa389b9030326",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF66CC,
              "opacity":1},
            "location":{
              "x":674,
              "y":70},
            "size":{
              "width":66,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cc2a79f8dac413f87724a3e31807165",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF66CC,
                  "opacity":1},
                "location":{
                  "x":674,
                  "y":70},
                "size":{
                  "width":66,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"463880cbb77c4a49b84b8899ebea5964",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":150,
              "y":72},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9f1a72c6bcf495ebb167e1aaa81b6e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":150,
                  "y":72},
                "size":{
                  "width":100,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1dd3b52607c446bfaa838a563b25a9de",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":120},
            "size":{
              "width":80,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 当前部件 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["1dd3b52607c446bfaa838a563b25a9de"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"a0c86a95f7d24ae7b947d75136fdb957",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":120},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 当前部件 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["a0c86a95f7d24ae7b947d75136fdb957"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"e1de0fb328184d43ad7e74002df27f37",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":120},
            "size":{
              "width":90,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 当前部件 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["e1de0fb328184d43ad7e74002df27f37"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"9dbe4aa24cde4b22b53173b3eeb3e1ed",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":120},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 d1 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["c22caad9519f43328e647852abedd08e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"7340f2278389424e90b2b2d18cb23ef7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":564,
              "y":70},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbed2899d8b34d3aaf2e3b4b1e3c41f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":564,
                  "y":70},
                "size":{
                  "width":100,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 studentInfo",
                      "target":{
                        "targetType":"page",
                        "url":"studentinfo.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d55e2fe1ece645cd920101a6d06f0abb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCC99CC,
              "opacity":1},
            "location":{
              "x":348,
              "y":72},
            "size":{
              "width":72,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdc1a193a1ec4685b7b79be811d5753f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCC99CC,
                  "opacity":1},
                "location":{
                  "x":348,
                  "y":72},
                "size":{
                  "width":72,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 selectCourse",
                      "target":{
                        "targetType":"page",
                        "url":"selectcourse.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c22caad9519f43328e647852abedd08e",
          "label":"d1",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":210},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"77cd1b7c00a2408f9fe38d6e4ae0e0fe",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e6c99b38b5124edca0d30db99c1844db",
                  "label":"",
                  "parentDynamicPanel":"c22caad9519f43328e647852abedd08e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold Oblique', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "fontStyle":"oblique",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF515151,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "size":{
                      "width":130,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8eda286f98a144a6ad0021b280cb5c01",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c22caad9519f43328e647852abedd08e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold Oblique', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "fontStyle":"oblique",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF515151,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCFF},
                        "size":{
                          "width":130,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/student/u15.png"}},
{
                  "id":"a6fb66c4bc144b3a8aff1894dc2e60ff",
                  "label":"",
                  "parentDynamicPanel":"c22caad9519f43328e647852abedd08e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF515151,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "location":{
                      "x":0,
                      "y":35},
                    "size":{
                      "width":170,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"74c004e2b83c4114baece629951c59a1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c22caad9519f43328e647852abedd08e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF515151,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCFF},
                        "location":{
                          "x":0,
                          "y":35},
                        "size":{
                          "width":170,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/student/u17.png"}},
{
                  "id":"165e0554c2f448efb060d20dca26a41f",
                  "label":"",
                  "parentDynamicPanel":"c22caad9519f43328e647852abedd08e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":110,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c3af2e6921fe4c23b15addf71964328a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c22caad9519f43328e647852abedd08e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":60},
                        "size":{
                          "width":110,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5d9ee0bb1cd44f2fbc26e935a004e4d9",
                  "label":"",
                  "parentDynamicPanel":"c22caad9519f43328e647852abedd08e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF515151,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "location":{
                      "x":0,
                      "y":85},
                    "size":{
                      "width":170,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"492351bebd78412cbff7e4563d8226c7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c22caad9519f43328e647852abedd08e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF515151,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCFF},
                        "location":{
                          "x":0,
                          "y":85},
                        "size":{
                          "width":170,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/student/u17.png"}},
{
                  "id":"bc7639e879b84609a0565f185b6afa7f",
                  "label":"",
                  "parentDynamicPanel":"c22caad9519f43328e647852abedd08e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF515151,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "location":{
                      "x":0,
                      "y":113},
                    "size":{
                      "width":170,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d23ba5d970214290afbe50d400643fb5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c22caad9519f43328e647852abedd08e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF515151,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCFF},
                        "location":{
                          "x":0,
                          "y":113},
                        "size":{
                          "width":170,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/student/u17.png"}},
{
                  "id":"9e209792db6a4ccdb0e5789a13725d15",
                  "label":"",
                  "parentDynamicPanel":"c22caad9519f43328e647852abedd08e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF515151,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "location":{
                      "x":290,
                      "y":38},
                    "size":{
                      "width":170,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3e2e6d81ca25477aa57fc0e3c54413c1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c22caad9519f43328e647852abedd08e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF515151,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCFF},
                        "location":{
                          "x":290,
                          "y":38},
                        "size":{
                          "width":170,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/student/u17.png"}},
{
                  "id":"f5a28140867b4059945a66a2a22c44bf",
                  "label":"",
                  "parentDynamicPanel":"c22caad9519f43328e647852abedd08e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":290,
                      "y":62},
                    "size":{
                      "width":110,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"56c52add537c4eb8b2d60b7de8231858",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c22caad9519f43328e647852abedd08e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":290,
                          "y":62},
                        "size":{
                          "width":110,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f47f97f1521345d79f1fc70b4d9e9b05",
                  "label":"",
                  "parentDynamicPanel":"c22caad9519f43328e647852abedd08e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF515151,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "location":{
                      "x":290,
                      "y":88},
                    "size":{
                      "width":170,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ca29545ddc0c40908be0b446757ffd22",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c22caad9519f43328e647852abedd08e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF515151,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCFF},
                        "location":{
                          "x":290,
                          "y":88},
                        "size":{
                          "width":170,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/student/u17.png"}},
{
                  "id":"f6ad8e46afac41289a1a854dfac66184",
                  "label":"",
                  "parentDynamicPanel":"c22caad9519f43328e647852abedd08e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF515151,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "location":{
                      "x":290,
                      "y":116},
                    "size":{
                      "width":170,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fd2f8f81d5df4ccbb94b4cfac6aff7c6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c22caad9519f43328e647852abedd08e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF515151,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCFF},
                        "location":{
                          "x":290,
                          "y":116},
                        "size":{
                          "width":170,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/student/u17.png"}},
{
                  "id":"def85010bcfa498f9acb24116176e9f8",
                  "label":"",
                  "parentDynamicPanel":"c22caad9519f43328e647852abedd08e",
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":170},
                    "size":{
                      "width":470,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"317d85811f644464ac67f7dc5ee72c5a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c22caad9519f43328e647852abedd08e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":170},
                        "size":{
                          "width":470,
                          "height":10}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/student/u33.png"}}]}]},
{
          "id":"901e12e345984f779ea10c61d49a2660",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6666FF,
              "opacity":1},
            "location":{
              "x":447,
              "y":72},
            "size":{
              "width":103,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ee091da53c945469dd7a2dde94b006b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6666FF,
                  "opacity":1},
                "location":{
                  "x":447,
                  "y":72},
                "size":{
                  "width":103,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 updatepwd",
                      "target":{
                        "targetType":"page",
                        "url":"updatepwd.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9dbc91f983044eac958d28e6a0b51c1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC99,
              "opacity":1},
            "location":{
              "x":348,
              "y":30},
            "size":{
              "width":250,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a17df9ba02f34b94bf98803f6aa8acb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC99,
                  "opacity":1},
                "location":{
                  "x":348,
                  "y":30},
                "size":{
                  "width":250,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf2b584652b34e849800af001878b64d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC99,
              "opacity":1},
            "location":{
              "x":468,
              "y":152},
            "size":{
              "width":250,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec379014b4f34011b23ae0cdad994479",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC99,
                  "opacity":1},
                "location":{
                  "x":468,
                  "y":152},
                "size":{
                  "width":250,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "23ffbefc7ab64a2e9fa4445a49579f02":{
      "scriptId":"u0"},
    "162ea1746bd44a86b83ca09f3abb360f":{
      "scriptId":"u1"},
    "cf9ce46af26241c69effa389b9030326":{
      "scriptId":"u2"},
    "2cc2a79f8dac413f87724a3e31807165":{
      "scriptId":"u3"},
    "463880cbb77c4a49b84b8899ebea5964":{
      "scriptId":"u4"},
    "b9f1a72c6bcf495ebb167e1aaa81b6e6":{
      "scriptId":"u5"},
    "1dd3b52607c446bfaa838a563b25a9de":{
      "scriptId":"u6"},
    "a0c86a95f7d24ae7b947d75136fdb957":{
      "scriptId":"u7"},
    "e1de0fb328184d43ad7e74002df27f37":{
      "scriptId":"u8"},
    "9dbe4aa24cde4b22b53173b3eeb3e1ed":{
      "scriptId":"u9"},
    "7340f2278389424e90b2b2d18cb23ef7":{
      "scriptId":"u10"},
    "bbed2899d8b34d3aaf2e3b4b1e3c41f5":{
      "scriptId":"u11"},
    "d55e2fe1ece645cd920101a6d06f0abb":{
      "scriptId":"u12"},
    "bdc1a193a1ec4685b7b79be811d5753f":{
      "scriptId":"u13"},
    "c22caad9519f43328e647852abedd08e":{
      "scriptId":"u14"},
    "e6c99b38b5124edca0d30db99c1844db":{
      "scriptId":"u15"},
    "8eda286f98a144a6ad0021b280cb5c01":{
      "scriptId":"u16"},
    "a6fb66c4bc144b3a8aff1894dc2e60ff":{
      "scriptId":"u17"},
    "74c004e2b83c4114baece629951c59a1":{
      "scriptId":"u18"},
    "165e0554c2f448efb060d20dca26a41f":{
      "scriptId":"u19"},
    "c3af2e6921fe4c23b15addf71964328a":{
      "scriptId":"u20"},
    "5d9ee0bb1cd44f2fbc26e935a004e4d9":{
      "scriptId":"u21"},
    "492351bebd78412cbff7e4563d8226c7":{
      "scriptId":"u22"},
    "bc7639e879b84609a0565f185b6afa7f":{
      "scriptId":"u23"},
    "d23ba5d970214290afbe50d400643fb5":{
      "scriptId":"u24"},
    "9e209792db6a4ccdb0e5789a13725d15":{
      "scriptId":"u25"},
    "3e2e6d81ca25477aa57fc0e3c54413c1":{
      "scriptId":"u26"},
    "f5a28140867b4059945a66a2a22c44bf":{
      "scriptId":"u27"},
    "56c52add537c4eb8b2d60b7de8231858":{
      "scriptId":"u28"},
    "f47f97f1521345d79f1fc70b4d9e9b05":{
      "scriptId":"u29"},
    "ca29545ddc0c40908be0b446757ffd22":{
      "scriptId":"u30"},
    "f6ad8e46afac41289a1a854dfac66184":{
      "scriptId":"u31"},
    "fd2f8f81d5df4ccbb94b4cfac6aff7c6":{
      "scriptId":"u32"},
    "def85010bcfa498f9acb24116176e9f8":{
      "scriptId":"u33"},
    "317d85811f644464ac67f7dc5ee72c5a":{
      "scriptId":"u34"},
    "901e12e345984f779ea10c61d49a2660":{
      "scriptId":"u35"},
    "9ee091da53c945469dd7a2dde94b006b":{
      "scriptId":"u36"},
    "9dbc91f983044eac958d28e6a0b51c1c":{
      "scriptId":"u37"},
    "a17df9ba02f34b94bf98803f6aa8acb6":{
      "scriptId":"u38"},
    "cf2b584652b34e849800af001878b64d":{
      "scriptId":"u39"},
    "ec379014b4f34011b23ae0cdad994479":{
      "scriptId":"u40"}}});