$axure.loadCurrentPage({
  "url":"student.html",
  "generationDate":new Date(1527499505937.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9fcc1975e2ee4476a2ef6c4b10a6d271",
    "type":"Axure:Page",
    "name":"student",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"23ffbefc7ab64a2e9fa4445a49579f02",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCFF},
            "location":{
              "x":142,
              "y":60},
            "size":{
              "width":578,
              "height":440}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"162ea1746bd44a86b83ca09f3abb360f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCFF},
                "location":{
                  "x":142,
                  "y":60},
                "size":{
                  "width":578,
                  "height":440}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/student/u0.png"}},
{
          "id":"cf9ce46af26241c69effa389b9030326",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":674,
              "y":70},
            "size":{
              "width":66,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cc2a79f8dac413f87724a3e31807165",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":674,
                  "y":70},
                "size":{
                  "width":66,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"463880cbb77c4a49b84b8899ebea5964",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":150,
              "y":72},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9f1a72c6bcf495ebb167e1aaa81b6e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":150,
                  "y":72},
                "size":{
                  "width":100,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1dd3b52607c446bfaa838a563b25a9de",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":120},
            "size":{
              "width":80,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 当前部件 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["1dd3b52607c446bfaa838a563b25a9de"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"a0c86a95f7d24ae7b947d75136fdb957",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":120},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 当前部件 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["a0c86a95f7d24ae7b947d75136fdb957"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"e1de0fb328184d43ad7e74002df27f37",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":120},
            "size":{
              "width":90,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 当前部件 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["e1de0fb328184d43ad7e74002df27f37"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"9dbe4aa24cde4b22b53173b3eeb3e1ed",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":120},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (表格) 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["7c321a6c48a94cf3a02546087bf672b5"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"7340f2278389424e90b2b2d18cb23ef7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":564,
              "y":70},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbed2899d8b34d3aaf2e3b4b1e3c41f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":564,
                  "y":70},
                "size":{
                  "width":100,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 studentInfo",
                      "target":{
                        "targetType":"page",
                        "url":"studentinfo.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c321a6c48a94cf3a02546087bf672b5",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":false,
          "style":{
            "location":{
              "x":320,
              "y":175},
            "size":{
              "width":200,
              "height":267},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd17287a55224d41bf3dc8ad310754c2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCFF},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2031e4bcae9042b5b91feffd9ee00018",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/student/u13.png"}},
{
              "id":"97d4f6421e1a4d45894785585a4415e6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCFF},
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ea43dca1eb184f21afb8bdc43f7d82e6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/student/u13.png"}},
{
              "id":"fc78bd1ae2004c3098f4261ad74e6eee",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCFF},
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"692cd4f282b24018be98a34a0a341faf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/student/u21.png"}},
{
              "id":"cdc7d972309b41a7b422f2e1a717ce55",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCFF},
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5ba54696478648f6a0796f79dd6eb6e9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/student/u15.png"}},
{
              "id":"1c21ec0f604c41ccbf542e1cd2f4f583",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCFF},
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"46e1e0d6779e4b88b543c8b331dfed07",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/student/u15.png"}},
{
              "id":"a39b09a31b9341928c14a07c945315e0",
              "label":"成绩表",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCFF},
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6be511003c2c4a2bb4811410bba2c645",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/student/成绩表_u23.png"}},
{
              "id":"28badf06a893495fbb689a2a3363d4c1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCFF},
                "location":{
                  "x":0,
                  "y":87},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9195bcb3567f489fa3e8df1a65a3d3a2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "location":{
                      "x":0,
                      "y":87},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/student/u13.png"}},
{
              "id":"b4b01e40a8c64ae7b42a600425493dfe",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCFF},
                "location":{
                  "x":100,
                  "y":87},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3e065ff995e243498c0be9b7330101ea",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "location":{
                      "x":100,
                      "y":87},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/student/u15.png"}},
{
              "id":"a773ddca88d948709d5d917c126e26b4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCFF},
                "location":{
                  "x":0,
                  "y":117},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b4be9a46a2724986a7cfb18a2db3bab3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "location":{
                      "x":0,
                      "y":117},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/student/u13.png"}},
{
              "id":"7dc7ce42eae94d90b0974f0b6bf79953",
              "label":"成绩表",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCFF},
                "location":{
                  "x":100,
                  "y":117},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e6f4103fa8d74c8c8657bad50e7b9250",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "location":{
                      "x":100,
                      "y":117},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/student/u15.png"}},
{
              "id":"ae8847622fa74dc2a49bf4888f7cba8b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCFF},
                "location":{
                  "x":0,
                  "y":147},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6549688334ff422894097ead16eab1b3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "location":{
                      "x":0,
                      "y":147},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/student/u13.png"}},
{
              "id":"af4cd573638643349640c409062c3268",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCFF},
                "location":{
                  "x":100,
                  "y":147},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"70a2cb18a0094d25abc4b8969995c632",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "location":{
                      "x":100,
                      "y":147},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/student/u15.png"}},
{
              "id":"9ace68993a284bfaafc5a7e334e94581",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCFF},
                "location":{
                  "x":0,
                  "y":177},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3f1da92474de4740bd0a76c8a58a39e9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "location":{
                      "x":0,
                      "y":177},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/student/u13.png"}},
{
              "id":"86eb582153e94630a5062257c4867abb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCFF},
                "location":{
                  "x":100,
                  "y":177},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"00fc667b4e994faa9bec7bed197e9f96",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "location":{
                      "x":100,
                      "y":177},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/student/u15.png"}},
{
              "id":"446607032c394589a9bb59ed64f900f2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCFF},
                "location":{
                  "x":0,
                  "y":207},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c84dacab200b4f9a93ce295ba56de851",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "location":{
                      "x":0,
                      "y":207},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/student/u13.png"}},
{
              "id":"4d804949964b42908533540ea092e7a2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCFF},
                "location":{
                  "x":100,
                  "y":207},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9714cc9876164a88b3c578d6a68545a0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "location":{
                      "x":100,
                      "y":207},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/student/u15.png"}},
{
              "id":"87774bcc52524da899dcbfa4d10a1e09",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCFF},
                "location":{
                  "x":0,
                  "y":237},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9690f27170a44e11a4902e95a303f6a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "location":{
                      "x":0,
                      "y":237},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/student/u45.png"}},
{
              "id":"07d085d65df545acade120a5dea8738e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCFF},
                "location":{
                  "x":100,
                  "y":237},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a6638dc683e34a568a26a6c9a6cfa723",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCFF},
                    "location":{
                      "x":100,
                      "y":237},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/student/u47.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "23ffbefc7ab64a2e9fa4445a49579f02":{
      "scriptId":"u0"},
    "162ea1746bd44a86b83ca09f3abb360f":{
      "scriptId":"u1"},
    "cf9ce46af26241c69effa389b9030326":{
      "scriptId":"u2"},
    "2cc2a79f8dac413f87724a3e31807165":{
      "scriptId":"u3"},
    "463880cbb77c4a49b84b8899ebea5964":{
      "scriptId":"u4"},
    "b9f1a72c6bcf495ebb167e1aaa81b6e6":{
      "scriptId":"u5"},
    "1dd3b52607c446bfaa838a563b25a9de":{
      "scriptId":"u6"},
    "a0c86a95f7d24ae7b947d75136fdb957":{
      "scriptId":"u7"},
    "e1de0fb328184d43ad7e74002df27f37":{
      "scriptId":"u8"},
    "9dbe4aa24cde4b22b53173b3eeb3e1ed":{
      "scriptId":"u9"},
    "7340f2278389424e90b2b2d18cb23ef7":{
      "scriptId":"u10"},
    "bbed2899d8b34d3aaf2e3b4b1e3c41f5":{
      "scriptId":"u11"},
    "7c321a6c48a94cf3a02546087bf672b5":{
      "scriptId":"u12"},
    "fd17287a55224d41bf3dc8ad310754c2":{
      "scriptId":"u13"},
    "2031e4bcae9042b5b91feffd9ee00018":{
      "scriptId":"u14"},
    "cdc7d972309b41a7b422f2e1a717ce55":{
      "scriptId":"u15"},
    "5ba54696478648f6a0796f79dd6eb6e9":{
      "scriptId":"u16"},
    "97d4f6421e1a4d45894785585a4415e6":{
      "scriptId":"u17"},
    "ea43dca1eb184f21afb8bdc43f7d82e6":{
      "scriptId":"u18"},
    "1c21ec0f604c41ccbf542e1cd2f4f583":{
      "scriptId":"u19"},
    "46e1e0d6779e4b88b543c8b331dfed07":{
      "scriptId":"u20"},
    "fc78bd1ae2004c3098f4261ad74e6eee":{
      "scriptId":"u21"},
    "692cd4f282b24018be98a34a0a341faf":{
      "scriptId":"u22"},
    "a39b09a31b9341928c14a07c945315e0":{
      "scriptId":"u23"},
    "6be511003c2c4a2bb4811410bba2c645":{
      "scriptId":"u24"},
    "28badf06a893495fbb689a2a3363d4c1":{
      "scriptId":"u25"},
    "9195bcb3567f489fa3e8df1a65a3d3a2":{
      "scriptId":"u26"},
    "b4b01e40a8c64ae7b42a600425493dfe":{
      "scriptId":"u27"},
    "3e065ff995e243498c0be9b7330101ea":{
      "scriptId":"u28"},
    "a773ddca88d948709d5d917c126e26b4":{
      "scriptId":"u29"},
    "b4be9a46a2724986a7cfb18a2db3bab3":{
      "scriptId":"u30"},
    "7dc7ce42eae94d90b0974f0b6bf79953":{
      "scriptId":"u31"},
    "e6f4103fa8d74c8c8657bad50e7b9250":{
      "scriptId":"u32"},
    "ae8847622fa74dc2a49bf4888f7cba8b":{
      "scriptId":"u33"},
    "6549688334ff422894097ead16eab1b3":{
      "scriptId":"u34"},
    "af4cd573638643349640c409062c3268":{
      "scriptId":"u35"},
    "70a2cb18a0094d25abc4b8969995c632":{
      "scriptId":"u36"},
    "9ace68993a284bfaafc5a7e334e94581":{
      "scriptId":"u37"},
    "3f1da92474de4740bd0a76c8a58a39e9":{
      "scriptId":"u38"},
    "86eb582153e94630a5062257c4867abb":{
      "scriptId":"u39"},
    "00fc667b4e994faa9bec7bed197e9f96":{
      "scriptId":"u40"},
    "446607032c394589a9bb59ed64f900f2":{
      "scriptId":"u41"},
    "c84dacab200b4f9a93ce295ba56de851":{
      "scriptId":"u42"},
    "4d804949964b42908533540ea092e7a2":{
      "scriptId":"u43"},
    "9714cc9876164a88b3c578d6a68545a0":{
      "scriptId":"u44"},
    "87774bcc52524da899dcbfa4d10a1e09":{
      "scriptId":"u45"},
    "9690f27170a44e11a4902e95a303f6a3":{
      "scriptId":"u46"},
    "07d085d65df545acade120a5dea8738e":{
      "scriptId":"u47"},
    "a6638dc683e34a568a26a6c9a6cfa723":{
      "scriptId":"u48"}}});