$axure.loadCurrentPage({
  "url":"updatepwd.html",
  "generationDate":new Date(1528189356989.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"967040005eba4a66bfd7d9ab18e7c247",
    "type":"Axure:Page",
    "name":"updatepwd",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"89a4bee5b141465fbb2f08015ac23c84",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":80},
            "size":{
              "width":350,
              "height":340}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43db3952b5de414d92ad956f2954e855",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":80},
                "size":{
                  "width":350,
                  "height":340}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/updatepwd/u0.png"}},
{
          "id":"48e4601208d94b449f7082b67e5715c6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":355,
              "y":310},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"7c168a66cdde4c11b78154dff619498e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":310,
              "y":150},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"71c5db8adac146abbba619e0a4be27ec",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCC99},
            "location":{
              "x":310,
              "y":215},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"51f2fb8998624778803205c9aef73aef",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCC99},
            "location":{
              "x":310,
              "y":250},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f13c2ef6639e45caab01b886c3a9b092",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":380,
              "y":196},
            "size":{
              "width":141,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76f6faa9d82c4aac86a2a9dcb74f7232",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":380,
                  "y":196},
                "size":{
                  "width":141,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "89a4bee5b141465fbb2f08015ac23c84":{
      "scriptId":"u0"},
    "43db3952b5de414d92ad956f2954e855":{
      "scriptId":"u1"},
    "48e4601208d94b449f7082b67e5715c6":{
      "scriptId":"u2"},
    "7c168a66cdde4c11b78154dff619498e":{
      "scriptId":"u3"},
    "71c5db8adac146abbba619e0a4be27ec":{
      "scriptId":"u4"},
    "51f2fb8998624778803205c9aef73aef":{
      "scriptId":"u5"},
    "f13c2ef6639e45caab01b886c3a9b092":{
      "scriptId":"u6"},
    "76f6faa9d82c4aac86a2a9dcb74f7232":{
      "scriptId":"u7"}}});