@startuml
actor 用户

用户-->系统:成功登陆该系统
alt 用户为老师
用户-> 课程:查询某一教授课程
课程 -> 学生信息列表:查询所授课程的学生信息列表
学生信息列表->用户:以二维表的行返学生列表
学生 ->实验:查询出已评定的实验
实验分数-->用户:显示实验的分数
else 用户为学生
用户 -> 课程: 查询某一课程
课程-> 实验:查询已评定的实验成绩
实验 --> 用户:显示已评定的实验成绩
实验分数-->用户:显示实验的分数
end
@enduml