@startuml
actor 教师
教师 -> 系统: 成功登录该系统
教师 -> 学生信息列表:查看所授课程的所有学生信息列表
学生信息列表 -> 教师:以二维表的格式返回
学生信息列表 -> 学生:点击进入实验成绩的评定

alt 所有实验已评定完成
学生 ->实验: 显示所有已评定的实验成绩
else 还有待评定的实验成绩
学生 ->实验: 显示待评定的实验成绩
教师-> 实验: 评定实验
end
实验 --> 学生信息列表:评定实验成果后返回到学生信息列表的页面


@enduml