$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1528189356700.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"562664168b3a49d8bee6f29d0c62dbef",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"31fdb90966894132b402a57e714d7404",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCFF},
            "location":{
              "x":360,
              "y":14},
            "size":{
              "width":380,
              "height":426}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39ec97943f6944b488ec9e1f896a6975",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCFF},
                "location":{
                  "x":360,
                  "y":14},
                "size":{
                  "width":380,
                  "height":426}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"1e669332516d47bf86a9295ea1d8c89e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":509,
              "y":90},
            "size":{
              "width":82,
              "height":84}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d35c5f12916c4e76b3823d3e42f05c49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":509,
                  "y":90},
                "size":{
                  "width":82,
                  "height":84}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"dffcb98b47904110a1bb9812b007007f",
          "label":"login",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":340},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If 选中状态值 s = 真)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["7353580114d14c1182dffb635cb24c12"]}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":true}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 student",
                      "target":{
                        "targetType":"page",
                        "url":"student.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 2<br> (Else If 选中状态值 t = 真)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["e91259cbd4554b4199f6e4b31e223138"]}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":true}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 teacher",
                      "target":{
                        "targetType":"page",
                        "url":"teacher.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e91259cbd4554b4199f6e4b31e223138",
          "label":"t",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":300},
            "size":{
              "width":100,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb19448c3e8344c08930c7676e841afd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":300},
                "size":{
                  "width":100,
                  "height":15}},
              "adaptiveStyles":{
}}]},
{
          "id":"7353580114d14c1182dffb635cb24c12",
          "label":"s",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":300},
            "size":{
              "width":100,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd7516b61f794189b6dea872d9a26318",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":300},
                "size":{
                  "width":100,
                  "height":15}},
              "adaptiveStyles":{
}}]},
{
          "id":"ebfd6b3d39774f3eabd0440031e33ba9",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":258},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 当前部件 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["ebfd6b3d39774f3eabd0440031e33ba9"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"3a64094062da4182ab271085fd0d4d59",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":184},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0476d761453e436d92c94d2f5ab53bdb",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":223},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a9f92d2d13134fec98e9ce67e7a3c037",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC99,
              "opacity":1},
            "location":{
              "x":410,
              "y":375},
            "size":{
              "width":300,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47a97f54dd8d43f38d86aca8cd3ac8d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC99,
                  "opacity":1},
                "location":{
                  "x":410,
                  "y":375},
                "size":{
                  "width":300,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50387aab8f5b4803b01c6584366a89c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":740,
              "y":223},
            "size":{
              "width":398,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94415cd7879a4e7fbece1907fc04fef6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":740,
                  "y":223},
                "size":{
                  "width":398,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "31fdb90966894132b402a57e714d7404":{
      "scriptId":"u0"},
    "39ec97943f6944b488ec9e1f896a6975":{
      "scriptId":"u1"},
    "1e669332516d47bf86a9295ea1d8c89e":{
      "scriptId":"u2"},
    "d35c5f12916c4e76b3823d3e42f05c49":{
      "scriptId":"u3"},
    "dffcb98b47904110a1bb9812b007007f":{
      "scriptId":"u4"},
    "e91259cbd4554b4199f6e4b31e223138":{
      "scriptId":"u5"},
    "fb19448c3e8344c08930c7676e841afd":{
      "scriptId":"u6"},
    "7353580114d14c1182dffb635cb24c12":{
      "scriptId":"u7"},
    "cd7516b61f794189b6dea872d9a26318":{
      "scriptId":"u8"},
    "ebfd6b3d39774f3eabd0440031e33ba9":{
      "scriptId":"u9"},
    "3a64094062da4182ab271085fd0d4d59":{
      "scriptId":"u10"},
    "0476d761453e436d92c94d2f5ab53bdb":{
      "scriptId":"u11"},
    "a9f92d2d13134fec98e9ce67e7a3c037":{
      "scriptId":"u12"},
    "47a97f54dd8d43f38d86aca8cd3ac8d8":{
      "scriptId":"u13"},
    "50387aab8f5b4803b01c6584366a89c6":{
      "scriptId":"u14"},
    "94415cd7879a4e7fbece1907fc04fef6":{
      "scriptId":"u15"}}});