$axure.loadCurrentPage({
  "url":"studentinfo.html",
  "generationDate":new Date(1527499506074.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4659cb8756034399b450a74ae9c38287",
    "type":"Axure:Page",
    "name":"studentInfo",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"03af19c03f0e41e6b1189b04239b0cd2",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":60},
            "size":{
              "width":460,
              "height":430}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99887a46e27b43c78e240f83758899ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":60},
                "size":{
                  "width":460,
                  "height":430}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/studentinfo/u0.png"}},
{
          "id":"2f86900b8d6548108756843b77413c0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":650,
              "y":80},
            "size":{
              "width":40,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5cae04bc84d431faf2f46e6354b6f3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":650,
                  "y":80},
                "size":{
                  "width":40,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a37b3d08506946d483d7e983d1a7b7f2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":320,
              "y":140},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"95f69dd281d04b748ca510232b109d1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":509,
              "y":145},
            "size":{
              "width":21,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8cb23c391bf4bbc8914ef5bd07e1ae0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":509,
                  "y":145},
                "size":{
                  "width":21,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0c05d20d07942519c51df8b82b1ff70",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":320,
              "y":175},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"cefc767654474d8eaaa8c2065c987ccc",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":320,
              "y":215},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e7e6939a55bb4615baa456a5de6e1971",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":320,
              "y":250},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8390aa5d9ad9469a93855e280b30a73b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":320,
              "y":285},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f849d5a350194eb2b50d6afd918c589d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":320,
              "y":355},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0a4e334fb7d8408b8d19ea4706462244",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":360,
              "y":410},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 updatepwd",
                      "target":{
                        "targetType":"page",
                        "url":"updatepwd.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"1608a979e84849d69d733f52300ff695",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":260,
              "y":80},
            "size":{
              "width":40,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65da6f6ee4cb41f08990b75d398de0af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":260,
                  "y":80},
                "size":{
                  "width":40,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 student",
                      "target":{
                        "targetType":"page",
                        "url":"student.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"143242f3f8304df3a2a455606700e339",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":320,
              "y":320},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "03af19c03f0e41e6b1189b04239b0cd2":{
      "scriptId":"u0"},
    "99887a46e27b43c78e240f83758899ea":{
      "scriptId":"u1"},
    "2f86900b8d6548108756843b77413c0e":{
      "scriptId":"u2"},
    "c5cae04bc84d431faf2f46e6354b6f3d":{
      "scriptId":"u3"},
    "a37b3d08506946d483d7e983d1a7b7f2":{
      "scriptId":"u4"},
    "95f69dd281d04b748ca510232b109d1f":{
      "scriptId":"u5"},
    "d8cb23c391bf4bbc8914ef5bd07e1ae0":{
      "scriptId":"u6"},
    "b0c05d20d07942519c51df8b82b1ff70":{
      "scriptId":"u7"},
    "cefc767654474d8eaaa8c2065c987ccc":{
      "scriptId":"u8"},
    "e7e6939a55bb4615baa456a5de6e1971":{
      "scriptId":"u9"},
    "8390aa5d9ad9469a93855e280b30a73b":{
      "scriptId":"u10"},
    "f849d5a350194eb2b50d6afd918c589d":{
      "scriptId":"u11"},
    "0a4e334fb7d8408b8d19ea4706462244":{
      "scriptId":"u12"},
    "1608a979e84849d69d733f52300ff695":{
      "scriptId":"u13"},
    "65da6f6ee4cb41f08990b75d398de0af":{
      "scriptId":"u14"},
    "143242f3f8304df3a2a455606700e339":{
      "scriptId":"u15"}}});