$axure.loadCurrentPage({
  "url":"teacher.html",
  "generationDate":new Date(1528189356930.04),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6b19f8cb8c7b4450837eb78c4f2252a5",
    "type":"Axure:Page",
    "name":"teacher",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"87d4dc642a17444ab06ef1c3ef3a8f1f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":-10},
            "size":{
              "width":630,
              "height":500}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9cdc92417d64830b73ffeef7d25cd21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":-10},
                "size":{
                  "width":630,
                  "height":500}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/teacher/u0.png"}},
{
          "id":"849d69ba93764d139af47b338952a78c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":150,
              "y":70},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"540c27edc1a148e1bf73e0a15caa5caf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":150,
                  "y":70},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"446e59d5e2dc4d679ce24cb946375f6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF66CC,
              "opacity":1},
            "location":{
              "x":710,
              "y":70},
            "size":{
              "width":40,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"829f0663f305426996bc28e0f75a1232",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF66CC,
                  "opacity":1},
                "location":{
                  "x":710,
                  "y":70},
                "size":{
                  "width":40,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37ed7ff8858740048be59116fb737254",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":580,
              "y":70},
            "size":{
              "width":100,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e26de8be9d43433e905bf77c7977d948",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":580,
                  "y":70},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 teacherInfo",
                      "target":{
                        "targetType":"page",
                        "url":"teacherinfo.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"976fe76867ab44b9930e17e960a5a340",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":195},
            "size":{
              "width":90,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"26cb7285a9744c11894c4b65cad95982",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCC99},
            "location":{
              "x":380,
              "y":140},
            "size":{
              "width":140,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"34926accf8a44c18b5564569f6dd64d5",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":195},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (表格) 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["dad22eb065bf42a4b0d4aff75ef71c7a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"cf11964bf76543b6a442a9ddbc4d509c",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":195},
            "size":{
              "width":70,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"dad22eb065bf42a4b0d4aff75ef71c7a",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":280},
            "size":{
              "width":400,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cebda764eaa14f289d5fb460f83b3ed0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"74d3dcbe4ef54f898a0fbad112a8365f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/teacher/u13.png"}},
{
              "id":"9acaf3c7b6964d19a10e12ab9d411510",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7e347688d2634808bad050e5f3784802",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/teacher/u13.png"}},
{
              "id":"8514e2f893e44a85a3be4908138bd2f4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"62161156c6024adab5aad86ce579e780",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/teacher/u13.png"}},
{
              "id":"43352d67dcbc48539ce7862e1bc27027",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"29e8cbb8f8d04e9991f7193582db924b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/teacher/u13.png"}},
{
              "id":"b4114317c59c414b9e0d982f785b085e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"614cbdbbdef148a9a6bdd6400111c1ec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/teacher/u13.png"}},
{
              "id":"3f43beeb8a8646339f7005dd9e578923",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"08f8de59488345d886b16e208a0329a4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/teacher/u13.png"}},
{
              "id":"deffcff553a343728bf0e5766bf8e673",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a66e464352a74cc8941ea4dc77fd7f36",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/teacher/u13.png"}},
{
              "id":"9769a4d4cfe940d8b55b509e8579a968",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9043fce8062a41088ff6dc89e20d3771",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/teacher/u13.png"}},
{
              "id":"2e861a1479584f038d842eda89ead175",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bbe7522edb1c440e8c2a542c02e76489",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/teacher/u13.png"}},
{
              "id":"db993926099d486e91dbb0d441c2c623",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b8e721e59019428ca6fa554c5cb52a11",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/teacher/u13.png"}},
{
              "id":"1f8da5251d0e465bbd649d1cd13739e7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8bb82f7db560434c95f9e4c4632a45db",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/teacher/u13.png"}},
{
              "id":"a2d8ab9574d344b3a3c5feafcfb74dca",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"28e1d99277714abd8b34847fbaae3b3d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/teacher/u13.png"}},
{
              "id":"38ab063c55d641d3bdee27ae3a4cec3b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"978d20a1bb2144068fdbdb0be64cea61",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/teacher/u45.png"}},
{
              "id":"dab6632602664ee49700906661dd5273",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1421b6cab1044c598edecdb6c7a71d64",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/teacher/u45.png"}},
{
              "id":"74b7e85765b04f44a59ae07c462c518d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1ddc850e1cdc4899aafd56da5853e2bd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/teacher/u45.png"}},
{
              "id":"d60082031d274162a8a1d99c1ad8bd3d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6666FF,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"751749a2ce29485da6962ca2f3429907",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF6666FF,
                      "opacity":1},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/teacher/u19.png"}},
{
              "id":"c3ea50dadc82403aad7852da5e5e13ba",
              "label":"access",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6666FF,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7433cdd67d4844eea810f4c12883f3cf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF6666FF,
                      "opacity":1},
                    "location":{
                      "x":300,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 makeScore",
                          "target":{
                            "targetType":"page",
                            "url":"makescore.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/teacher/u19.png"}},
{
              "id":"d5dd38e26fa44e87a57d3abb60f17d75",
              "label":"access",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6666FF,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ae1150c83ee241519b7a2b180ff59dc9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF6666FF,
                      "opacity":1},
                    "location":{
                      "x":300,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/teacher/u19.png"}},
{
              "id":"6433aaf9a12841aa8112cbd52a29a13d",
              "label":"access",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6666FF,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9464efded05447c99ebf02504524e6c3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF6666FF,
                      "opacity":1},
                    "location":{
                      "x":300,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/teacher/u19.png"}},
{
              "id":"04983256b9f44d49ac2709f8cde22908",
              "label":"access",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6666FF,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f45ea39a4eb74681a202d562f4f32150",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF6666FF,
                      "opacity":1},
                    "location":{
                      "x":300,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/teacher/access_u51.png"}}]},
{
          "id":"d12fa9b0637a4132a99c87fe4363e9fa",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":195},
            "size":{
              "width":70,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"fe654a50c0c24ae4b72fbd4076f25e1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":350,
              "y":70},
            "size":{
              "width":70,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bdf258cb6a34c018b2220096ccbfa8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":350,
                  "y":70},
                "size":{
                  "width":70,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 selectCourse",
                      "target":{
                        "targetType":"page",
                        "url":"selectcourse.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02276658598b4d12904997731ed4be71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCC99FF,
              "opacity":1},
            "location":{
              "x":460,
              "y":70},
            "size":{
              "width":110,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1474ecce35242b4ae052362215b795e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCC99FF,
                  "opacity":1},
                "location":{
                  "x":460,
                  "y":70},
                "size":{
                  "width":110,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 updatepwd",
                      "target":{
                        "targetType":"page",
                        "url":"updatepwd.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"508836c521c748f7828492b5327d5cf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC99,
              "opacity":1},
            "location":{
              "x":390,
              "y":20},
            "size":{
              "width":250,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98a82e191b27471e8fe301d791b4ebc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC99,
                  "opacity":1},
                "location":{
                  "x":390,
                  "y":20},
                "size":{
                  "width":250,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e7c2329b513438dbe0ab09a31ce8fdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC99,
              "opacity":1},
            "location":{
              "x":450,
              "y":230},
            "size":{
              "width":295,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9716ad159384e4b9dac3ed1741cfd6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC99,
                  "opacity":1},
                "location":{
                  "x":450,
                  "y":230},
                "size":{
                  "width":295,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "87d4dc642a17444ab06ef1c3ef3a8f1f":{
      "scriptId":"u0"},
    "a9cdc92417d64830b73ffeef7d25cd21":{
      "scriptId":"u1"},
    "849d69ba93764d139af47b338952a78c":{
      "scriptId":"u2"},
    "540c27edc1a148e1bf73e0a15caa5caf":{
      "scriptId":"u3"},
    "446e59d5e2dc4d679ce24cb946375f6d":{
      "scriptId":"u4"},
    "829f0663f305426996bc28e0f75a1232":{
      "scriptId":"u5"},
    "37ed7ff8858740048be59116fb737254":{
      "scriptId":"u6"},
    "e26de8be9d43433e905bf77c7977d948":{
      "scriptId":"u7"},
    "976fe76867ab44b9930e17e960a5a340":{
      "scriptId":"u8"},
    "26cb7285a9744c11894c4b65cad95982":{
      "scriptId":"u9"},
    "34926accf8a44c18b5564569f6dd64d5":{
      "scriptId":"u10"},
    "cf11964bf76543b6a442a9ddbc4d509c":{
      "scriptId":"u11"},
    "dad22eb065bf42a4b0d4aff75ef71c7a":{
      "scriptId":"u12"},
    "cebda764eaa14f289d5fb460f83b3ed0":{
      "scriptId":"u13"},
    "74d3dcbe4ef54f898a0fbad112a8365f":{
      "scriptId":"u14"},
    "43352d67dcbc48539ce7862e1bc27027":{
      "scriptId":"u15"},
    "29e8cbb8f8d04e9991f7193582db924b":{
      "scriptId":"u16"},
    "deffcff553a343728bf0e5766bf8e673":{
      "scriptId":"u17"},
    "a66e464352a74cc8941ea4dc77fd7f36":{
      "scriptId":"u18"},
    "d60082031d274162a8a1d99c1ad8bd3d":{
      "scriptId":"u19"},
    "751749a2ce29485da6962ca2f3429907":{
      "scriptId":"u20"},
    "9acaf3c7b6964d19a10e12ab9d411510":{
      "scriptId":"u21"},
    "7e347688d2634808bad050e5f3784802":{
      "scriptId":"u22"},
    "b4114317c59c414b9e0d982f785b085e":{
      "scriptId":"u23"},
    "614cbdbbdef148a9a6bdd6400111c1ec":{
      "scriptId":"u24"},
    "9769a4d4cfe940d8b55b509e8579a968":{
      "scriptId":"u25"},
    "9043fce8062a41088ff6dc89e20d3771":{
      "scriptId":"u26"},
    "c3ea50dadc82403aad7852da5e5e13ba":{
      "scriptId":"u27"},
    "7433cdd67d4844eea810f4c12883f3cf":{
      "scriptId":"u28"},
    "8514e2f893e44a85a3be4908138bd2f4":{
      "scriptId":"u29"},
    "62161156c6024adab5aad86ce579e780":{
      "scriptId":"u30"},
    "3f43beeb8a8646339f7005dd9e578923":{
      "scriptId":"u31"},
    "08f8de59488345d886b16e208a0329a4":{
      "scriptId":"u32"},
    "2e861a1479584f038d842eda89ead175":{
      "scriptId":"u33"},
    "bbe7522edb1c440e8c2a542c02e76489":{
      "scriptId":"u34"},
    "d5dd38e26fa44e87a57d3abb60f17d75":{
      "scriptId":"u35"},
    "ae1150c83ee241519b7a2b180ff59dc9":{
      "scriptId":"u36"},
    "db993926099d486e91dbb0d441c2c623":{
      "scriptId":"u37"},
    "b8e721e59019428ca6fa554c5cb52a11":{
      "scriptId":"u38"},
    "1f8da5251d0e465bbd649d1cd13739e7":{
      "scriptId":"u39"},
    "8bb82f7db560434c95f9e4c4632a45db":{
      "scriptId":"u40"},
    "a2d8ab9574d344b3a3c5feafcfb74dca":{
      "scriptId":"u41"},
    "28e1d99277714abd8b34847fbaae3b3d":{
      "scriptId":"u42"},
    "6433aaf9a12841aa8112cbd52a29a13d":{
      "scriptId":"u43"},
    "9464efded05447c99ebf02504524e6c3":{
      "scriptId":"u44"},
    "38ab063c55d641d3bdee27ae3a4cec3b":{
      "scriptId":"u45"},
    "978d20a1bb2144068fdbdb0be64cea61":{
      "scriptId":"u46"},
    "dab6632602664ee49700906661dd5273":{
      "scriptId":"u47"},
    "1421b6cab1044c598edecdb6c7a71d64":{
      "scriptId":"u48"},
    "74b7e85765b04f44a59ae07c462c518d":{
      "scriptId":"u49"},
    "1ddc850e1cdc4899aafd56da5853e2bd":{
      "scriptId":"u50"},
    "04983256b9f44d49ac2709f8cde22908":{
      "scriptId":"u51"},
    "f45ea39a4eb74681a202d562f4f32150":{
      "scriptId":"u52"},
    "d12fa9b0637a4132a99c87fe4363e9fa":{
      "scriptId":"u53"},
    "fe654a50c0c24ae4b72fbd4076f25e1b":{
      "scriptId":"u54"},
    "7bdf258cb6a34c018b2220096ccbfa8e":{
      "scriptId":"u55"},
    "02276658598b4d12904997731ed4be71":{
      "scriptId":"u56"},
    "e1474ecce35242b4ae052362215b795e":{
      "scriptId":"u57"},
    "508836c521c748f7828492b5327d5cf2":{
      "scriptId":"u58"},
    "98a82e191b27471e8fe301d791b4ebc0":{
      "scriptId":"u59"},
    "0e7c2329b513438dbe0ab09a31ce8fdd":{
      "scriptId":"u60"},
    "c9716ad159384e4b9dac3ed1741cfd6d":{
      "scriptId":"u61"}}});